In [32]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [22]:
true_w=torch.tensor([2,3.4,-12])
true_b=23.3
features, labels=d2l.synthetic_data(true_w,true_b,1000)

In [23]:
def load_array(data_arrays, batch_size, is_train=True):
    dataset=data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [24]:
batch_size=10
data_iter=load_array((features, labels), batch_size)

In [25]:
next(iter(data_iter))

[tensor([[ 1.3699, -1.0095, -0.8440],
         [-0.0338, -0.1680, -0.8426],
         [ 1.2005, -0.8599, -0.2113],
         [-0.8127,  1.8454, -0.3569],
         [ 0.0038, -0.9881,  1.9547],
         [ 0.3005, -0.3949,  1.7346],
         [ 0.0441,  2.0579, -1.4013],
         [-0.0715, -0.6176, -0.0474],
         [-0.0782, -0.3567,  0.7442],
         [-0.4057,  0.0996, -0.3821]]),
 tensor([[32.7425],
         [32.7746],
         [25.3152],
         [32.2315],
         [-3.5102],
         [ 1.7334],
         [47.1925],
         [21.6328],
         [12.9981],
         [27.4081]])]

In [26]:
next(iter(data_iter))

[tensor([[-0.2397,  1.1406,  0.5391],
         [ 1.3836,  0.6998, -0.0939],
         [-1.2803, -0.4944, -0.4615],
         [ 0.5608,  0.7564,  1.0508],
         [ 1.3030, -0.9130, -0.9615],
         [-0.9724, -0.8909, -2.6463],
         [ 2.0777, -0.8665,  0.0528],
         [ 0.1405,  0.4248,  1.3131],
         [-0.7177,  0.5858, -0.3547],
         [ 0.7383, -0.6210, -0.4856]]),
 tensor([[20.2201],
         [29.5839],
         [24.5882],
         [14.3902],
         [34.3324],
         [50.0732],
         [23.8716],
         [ 9.2744],
         [28.1410],
         [28.5083]])]

In [27]:
from torch import nn
net = nn.Sequential(nn.Linear(3,1))

In [28]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [29]:
loss = nn.MSELoss()

In [30]:
trainer = torch.optim.SGD(net.parameters(),lr=0.03)

In [31]:
num_epochs=3
for epoch in range(num_epochs):
    for X,y in data_iter:
        l=loss(net(X),y)
        # 反向传播计算梯度前梯度清零
        # 注意梯度清零的对象是optimizer而不是net
        trainer.zero_grad()
        # 反向传播计算梯度（计算图）
        l.backward()
        # 随机梯度下降（SGD）更新参数
        trainer.step()
    l=loss(net(features),labels)
    print(f'epoch:{epoch+1}, loss:{l:f}')

epoch:1, loss:0.003789
epoch:2, loss:0.000104
epoch:3, loss:0.000103


In [ ]:
w=net[0].weight.data
print('w的估计误差：',true_w-w.reshape(true_w.shape))
b=net[0].bias.data
print('b的估计误差：',true_b-b)

w的估计误差： tensor([ 6.6638e-05,  1.2589e-04, -2.0027e-04])
b的估计误差： tensor([0.0004])
