In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
# 自定义层
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        # 张量的每个元素减去它的均值
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8,128),CenteredLayer())

In [5]:
Y = net(torch.rand(4,8))
Y.mean()

tensor(-7.4506e-09, grad_fn=<MeanBackward0>)

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data)+self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 9.6938e-01,  2.2814e+00,  9.6324e-04],
        [-1.4651e+00, -2.7074e+00, -2.4191e-01],
        [ 8.3299e-01, -1.2597e+00,  4.5961e-01],
        [ 3.9359e-01,  8.4117e-01,  5.5459e-01],
        [-2.7527e-03,  1.9553e-01, -2.3930e-01]], requires_grad=True)

In [8]:
linear(torch.rand(2,5))

tensor([[0.7155, 0.0674, 0.4519],
        [0.3089, 0.0000, 0.2545]])

In [9]:
net = nn.Sequential(MyLinear(64,8), MyLinear(8,1))
net(torch.rand(3,64))

tensor([[0.0000],
        [2.4866],
        [0.0000]])