## 汇聚层  
汇聚层不包含参数，为固定形状的窗口来遍历每个位置  
我们通常计算汇聚窗口中所有元素的最大值（最大汇聚层）或平均值（平均汇聚层）

In [1]:
import torch
from torch import nn
from d2l import torch as d2l

In [10]:
def pool2d(X, pool_size, mode='max'):
    p_h,p_w = pool_size
    Y = torch.zeros((X.shape[0]-p_h+1, X.shape[1]-p_w+1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i,j] = X[i:i+p_h,j:j+p_w].max()
            elif mode == 'avg':
                Y[i,j] = X[i:i+p_h,j:j+p_w].mean()
    return Y

In [11]:
X = torch.tensor([[0.0,1.0,2.0],[3.0,4.0,5.0],[6.0,7.0,8.0]])
print(pool2d(X,(2,2)))

tensor([[4., 5.],
        [7., 8.]])


In [12]:
print(pool2d(X,(2,2),'avg'))

tensor([[2., 3.],
        [5., 6.]])


In [20]:
X = torch.arange(16, dtype=torch.float32).reshape(1,1,4,4)
X,X.shape

(tensor([[[[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.],
           [ 8.,  9., 10., 11.],
           [12., 13., 14., 15.]]]]),
 torch.Size([1, 1, 4, 4]))

默认情况下，深度学习框架中的步幅与汇聚窗口大小相同。  
（3，3）的汇聚窗口对应（3，3）的步幅

In [21]:
pool2d = nn.MaxPool2d(3)
pool2d(X)

tensor([[[[10.]]]])

In [22]:
# 手动设定步幅和填充
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [23]:
pool2d = nn.MaxPool2d((2,3),stride=(2,3),padding=(0,1))
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

## 多个通道  
在处理多通道输入数据时，**汇聚层在每个输入通道上单独运算**，而不是像卷积层一样在通道上对输入进行汇总。   
这意味着汇聚层的**输出通道数与输入通道数相同**

**注意torch.cat()和torch.stack()的区别**  
torch.cat()是将两个张量在原有的某个维度上拼接  
&nbsp;&nbsp;&nbsp;&nbsp;X的形状是1x1x4x4。下文的代码将在第二个维度上拼接，形状变为1x2x4x4  
torch.stack()是将两个张量在**新**的维度上堆叠  
&nbsp;&nbsp;&nbsp;&nbsp;使用torch.stack()将使X的形状变为1x2x1x4x4  

In [24]:
X = torch.cat((X,X+1),1)
X.shape

torch.Size([1, 2, 4, 4])

In [25]:
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])